namespace :my_tasks do
  # タスクの説明を入れる
  desc 'テスト用のタスクです。'
  # hello_worldという名前のタスクを定義する
  task :hello_world do
    # ブロックの中がタスクとして実行される処理になる
    puts 'Hello, world!'
  end
end

require 'rake/testtask'

Rake::TestTask.new do |t|
  t.pattern = 'test/**/*_test.rb'
end

task default: :test
